SELECT [Id]
      ,[PrdCodigo]
      ,[PrdNombre]
      ,[CatId]
      ,[PrvId]
      ,[PrdCantPorUnidad]
      ,[PrdPrecioUnidad]
      ,[PrdStockMinimo]
      ,[PrdStock]
      ,[PrdEstatus]
      ,[FechaCreacion]
      ,[CreadoPor]
      ,[FechaActualizacion]
      ,[ActualizadoPor]
      ,[PrdFoto1]
      ,[PrdFoto2]
  FROM [Inventario].[dbo].[Producto]
